
service: image-optimizer

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 512
  timeout: 10
  stage: dev

functions:
  imgOptimize:
    handler: handler.imgOptimize
    events:
      - http:
          path: imgOptimize
          method: get
          cors: true